name: 测试

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - beta

jobs:
  Notify:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Push ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send Notify
        uses: ./
        with:
          notify-url: ${{ secrets.NOTIFY_URL }}
          notify-project: '测试 Notify'
          deploy-success: 'false'
          add-info: '附加信息'
